# Style/Documentation проверяет документационные комментарии.
# Здесь мы отключаем эту проверку, потому что она жалуется на отсутствие документационного комментария верхнего уровня для класса.
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 60 # Увеличиваем максимальное количество строк в блоке до 60 или больше, чтобы избежать предупреждения.

# Style/StringLiterals проверяет последовательное использование строк в одинарных и двойных кавычках.
# Мы отключаем эту проверку, чтобы разрешить использование как одинарных, так и двойных кавычек.
Style/StringLiterals:
  Enabled: false

# Layout/TrailingWhitespace проверяет наличие пробелов в конце строк.
# Мы отключаем эту проверку, потому что она жалуется на наличие пробелов в конце строк.
Layout/TrailingWhitespace:
  Enabled: false

Layout/LineLength:
  Max: 150 # Увеличиваем максимальную длину строки до 150 символов или больше, чтобы избежать предупреждения.