# AllCops section is a configuration that is applied globally to all cops.
# It allows you to configure RuboCop's global behavior.

AllCops:
  Exclude:
    - 'vendor/**/*' # Exclude vendored files
    - 'db/schema.rb' # Exclude the schema file

# Style/Documentation cop checks for documentation comments.
# Here we're excluding this cop because it's complaining about missing top-level documentation comment for class.
Style/Documentation:
  Enabled: false

# Metrics/BlockLength cop checks the length of blocks.
# Here we're increasing the maximum allowed lines per block to 40.
Metrics/BlockLength:
  Max: 40

# Style/StringLiterals cop checks for consistent use of single-quoted and double-quoted strings.
# We're disabling this cop to allow both single and double quotes.
Style/StringLiterals:
  Enabled: false

# Layout/TrailingWhitespace cop checks for trailing whitespace.
# We're disabling this cop because it's complaining about trailing whitespace.
Layout/TrailingWhitespace:
  Enabled: false
