name: Ruby CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Check out code
      uses: actions/checkout@v2

    - name: Clean coverage directory
      run: rm -rf coverage

    - name: Install dependencies
      run: gem install bundler && bundle install

    - name: Run tests
      run: bundle exec rspec

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Check out code
      uses: actions/checkout@v2

    - name: Clean coverage directory
      run: rm -rf coverage

    - name: Install dependencies
      run: gem install bundler && bundle install

    - name: Run RuboCop
      run: bundle exec rubocop

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Check out code
      uses: actions/checkout@v2

    - name: Clean coverage directory
      run: rm -rf coverage

    - name: Install dependencies
      run: gem install bundler && bundle install

    - name: Run coverage tests
      run: |
        bundle exec rspec --format progress
        echo "Running SimpleCov"
        bundle exec rspec
        echo "Collecting SimpleCov report"
        mkdir coverage
        mv coverage/.resultset.json ./coverage/.resultset.json
      env:
        RAILS_ENV: test
        SIMPLECOV: true
